#!/usr/bin/python

import argparse
import sys
from tabulate import tabulate
import app

def print_table(table):
    print(tabulate(table , headers=["Task Id" , "Task" , "Deadline" , "Status"] , tablefmt="github"))


parser = argparse.ArgumentParser(description="Command line task tracker" , epilog="")
parser.add_argument("--mark" , "-M" , help="Mark you task complete , pass task id" , dest="mark" , metavar='')
parser.add_argument("--delete" , "-D" , help="Delete your tasks , pass task id" , dest="delete" , metavar='')
parser.add_argument("--add-task" , "-T" , help="Add some other task" , action='store_true' , dest='task')
parser.add_argument("--fetch-all" , "-A" , help="Get all of your tasks" , action='store_true' , dest='all_tasks')
parser.add_argument("--fetch-com" , "-C" , help="Get list of completed tasks" , action='store_true' , dest="com")
parser.add_argument("--fetch-incom" , "-I" , help="Get list of incomplete tasks" , action='store_true' , dest="icom")

args = parser.parse_args()


if args.task:
    task = input("What is the Task :> ")
    deadline = input("Deadline of this task :> ")
    app.create_task(task, deadline)
    print("Task Added")

if args.all_tasks:
    table = app.fetch_all()
    print_table(table)

if args.mark:
    app.mark_complete(args.mark)

if args.com:
    table = app.fetch_completed()
    print_table(table)

if args.delete:
    app.delete_record(args.delete)
    print("Task deleted")

if args.icom:
    table = app.fetch_incomplete()
    print_table(table)
    

